### ISSUE TITLE
registration pipeline for seqFISH

### ISSUE THREAD

**Issue by pdichiaro** [spacetx/starfish#1644] opened 2019-11-08 15:38 UTC
As image registration approach I use 2d similarity transformation to learn translation linear shifts (reference stack is DAPI) and then apply it for re-sampling of images across imaging rounds. While nuclei are perfect aligned, spots arising from the same target are distant across rounds; to match them during spot decoding I need to increase a lot the search radius (>7 pixel) and in case of crowded data it could be complex and problematic.

I was wondering if I should add a different spot registration approach like affine transformation   to have a more accurate spot alignment across rounds. 

Which registration pipeline do you suggest for seqFISH?

**Comment by ambrosejcarr** [comment] 2019-11-18 21:13
Hey @pdichiaro If I'm understanding your question properly, which is to say that you've observed that nuclei images taken in each round are perfectly aligned by a translational registration, it suggests to me that you don't have any rotation/scale/shear transformations on your tissue. This implies that your spots are moving _locally_ across rounds, that an affine transformation would not improve upon the spot alignment, and that you are in fact using the correct registration pipeline. Please let me know if I interpreted this properly. 

If I did, there are three solutions I see, one of which is to continue as you've been doing:

1. Continue as you are doing. Do you have concerns with this approach? Are there spots that are being missed? 
2. Run an iterative closest point algorithm based on an arbitrary start round to identify alignment -- this is similar to the local search, except that you don't have a maximum search radius
3. We are also working on a graph based solution that attempts to optimize in cases where there are multiple possible assignments for a point, that's currently in PR: #1613 

cc @dganguli

**Comment by pdichiaro** [comment] 2019-11-19 16:15
Hi @ambrosejcarr, you interpreted that well bravusr spots are moving locally across rounds. Do you think that  it is not so necessary to use fiduciary beads for learning any rotation/scale/shear transformations and so for improving spot registration?
If I continue as I am doing I have to increase a lot the search radius to detect the majority of spots.

**Comment by neuromusic** [comment] 2020-03-19 00:22
Hi @pdichiaro! I'm going to close this issue since its not a bug or feature request. We're starting to point users to image.sc for user support. If you're still facing this challenge, can you ask over there and tag the post with "starfish"?

**Closed by neuromusic** 2020-03-19 00:22 UTC
Labels: question
