### ISSUE TITLE
Allow Filter CLI + API to dump pngs

### ISSUE THREAD

**Issue by ambrosejcarr** [spacetx/starfish#157] opened 2018-05-11 17:43 UTC
Filter methods should have an option to dump pngs for easy feedback + viewing.

**Comment by ttung** [comment] 2018-09-21 17:12
We can save to TIFFs now.  Closing this barring any objections from @dganguli.

**Comment by joshmoore** [comment] 2018-09-21 18:43
@dganguli : I think the difference to what you are looking for in #603 is something that ties the files together in the fiji space like `experiment.json` does for sptx (which led me to add the reader idea back to 603)

**Comment by dganguli** [comment] 2018-09-21 18:52
ah yeah. in other words, ImageStack writes an FOV into spaceTx format. And you can go on and load any tile in FIJI if you use the tiff option. 

The problem is that FIJI doesn't open files in spaceTx file format, hence #603.

I say we close this issue in favor of #603.

**Closed by dganguli** 2018-09-21 18:52 UTC
Labels: enhancement, usability
